module.exports = {
    alps: require('./alps'),
    button: require('./button'),
    choc: require('./choc'),
    chocmini: require('./chocmini'),
    diode: require('./diode'),
    jstph: require('./jstph'),
    jumper: require('./jumper'),
    mx: require('./mx'),
    oled: require('./oled'),
    oled_128x64: require('./oled_128x64'),
    omron: require('./omron'),
    pad: require('./pad'),
    promicro: require('./promicro'),
    rgb: require('./rgb'),
    rotary: require('./rotary'),
    scrollwheel: require('./scrollwheel'),
    slider: require('./slider'),
    trrs: require('./trrs'),
    via: require('./via'),
    nice_nano_pretty: require('./nice_nano_pretty'),
    nice_nano_rot: require('./nice_nano_rot'),
    sk6812minie: require('./sk6812mini-e')
}